### ISSUE TITLE
pyzpl doesn't parse subtrees if the parent has a value

### ISSUE THREAD

**Issue by jwmelto** [mbarkhau/pyzpl#1]
This is (as far as I can tell) valid ZPL. The C API has no trouble with it:

    thing = foo
        bar = baz
    
    thing = flu
        bar = bat
    
     thing
        bar = bar

However, if you load such a config file into `pyzpl` there is no way to iterate over the `thing` instances and no way to access the `bar` values

    cfg = pyzpl.load( open(path, "r") )
    thing = cfg.get("thing")
    assert thing == u'thing'

**Comment by mbarkhau** [comment]
Without any changes to the library, I'll just point you to the `pyzpl.load_stream` function.

```ipython
In [10]: data = io.BytesIO(b"""
    ...: thing = foo
    ...:     bar = baz
    ...:
    ...: thing = flu
    ...:     bar = bat
    ...:
    ...: thing
    ...:     bar = bar
    ...: """)

In [12]: for names, value in pyzpl.load_stream(data):
    ...:     print(names, value)
('thing',) foo
('bar',) baz
('thing',) flu
('bar',) bat
('thing', 'bar') bar
```

If this isn't enough, I think you'll need to provide more input.

**Comment by jwmelto** [comment]
load_stream() has a different function than load(). load() returns a **dict** (tree) which more closely reflects the configuration. Note in your output:

    ('thing',) foo
    ('bar',) baz
    ('thing',) flu
    ('bar',) bat
    ('thing', 'bar') bar

the two 'bar' items subordinate to value-qualified 'thing' blocks lose context. That is, the last 'bar' item is correctly qualified as `('thing','bar')` but the prior two are just `('bar',)`

In more detail, in the [C API](http://czmq.zeromq.org/czmq4-0:zconfig), I can do this:

    zconfig_t* cfg = zconfig_load("/path/to/file");
    zconfig_t* thing = zconfig_locate(cfg, "thing");
    /* find the "flu" item */
    while (thing)
    {
        char* name = zconfig_value(thing);
        if (name && strcmp(name, "flu") == 0) {
            char* bar = zconfig_get(thing, "bar", "");
            printf("thing/bar where thing=flu is %s\n", bar);
            thing = 0;
            break;
        }
        /* not flu, get the next one */
        do
        {
            thing = zconfig_next(thing);
        } while (thing && strcmp(zconfig_name(thing), "thing") == 0);
    }

That's an (inelegant) example of walking a tree and finding a sub-tree with a matching value. Is there any way to do the same thing with **pyzpl**?

**Comment by mbarkhau** [comment]
I think `pyzpl.load_stream` can work for you, it's just that you're input is structured in a way that pyzpl handles differently than you expect. In particular the issue is with the property assignment followed by another indented property assignment.

```
thing = foo
    bar = baz
```

The spec is not completely clear on how this should be treated. Thinking about it, I don't even know how this would even be parsed. Maybe something like this?

```
{"thing": {"root": "foo", "bar": "baz"}}
```

If so, maybe you can change your input to this.

```
thing
    root = foo
    bar = baz
```

Which should produce the following from  `pyzpl.load_stream`.

```
In [12]: for names, value in pyzpl.load_stream(data):
    ...:     print(names, value)
('thing', 'root') foo
('thing', 'bar') baz
('thing', 'root') flu
('thing', 'bar') bat
('thing', 'bar') bar
```

**Comment by jwmelto** [comment]
I don't think this satisfies the intent of the ZPL. In particular, how would one query the parsed document and find the subordinate "thing" attributes for a given value. That is, how do you find the `bar` value when `thing` (or `thing/root` in your case) is equal to `flu`?

While the Python `dict` is a useful representation for the children, it is incomplete. It appears to me that your implementation allows a node to have a value or children, but not both. I think the spec allows this. As noted, the C API provides access to this detail.

I think you are confirming that **pyzpl** is not adequate for my purposes. I'll either look elsewhere, or roll my own. Thanks.

**Comment by mbarkhau** [comment]
As it stands, pyzpl doesn't support this no. While it may be that the C implementation works this way, from reading [the spec](https://rfc.zeromq.org/spec:4/ZPL/), it's not totally clear to me that this is clearly defined behaviour.  Note that in the example there is no case of a name that has both a value as well as a subtree associated with it.

I will say that streaming items is a valid use case and the current API is not particularly convenient for parsing gigabytes of data. Perhaps you would like to suggest a different API that would work for you. If you're not married to your data layout, maybe something like this would work. 

```
In [11]: for name, children in pyzpl.load_item_stream(buffer):
    ...:     print(repr(name), children)
'thing' {'root': 'foo', 'bar': 'baz'}
'thing' {'root': 'flu', 'bar': 'bat'}
'thing' {'bar': 'bar'}
```

**Comment by jwmelto** [comment]
In my particular case, the primary users of the ZPL are C++, so the utility of the C API to access sub-trees is very useful. I only need a Python interface to the config so that an engineering web interface can function. It's not worth re-designing existing implementation to work around this limitation of **pyzpl**.

I would say, though that the spec says 

> ZPL is designed to represent a property set, where each property has a name and a value. Properties are hierarchical, i.e. properties can contain other properties.

This seems unambiguous to me (although I think it would be more clear to say "each property has a name and an *optional* value"). One could argue that *property set* implies set-like behavior, that is, key uniqueness. YMMV.

I'll be thinking about how to adapt **pyzpl** to support richer use cases.

**Comment by jwmelto** [comment]
I'm very close to having a solution, which I will be happy to share. However, I've run into a fundamental limitation in how `pyzpl.load_stream` works. As you noted earlier, even if the ZPL were modified, 

>Which should produce the following from pyzpl.load_stream.
>
>`In [12]: for names, value in pyzpl.load_stream(data):`
>`    ...:     print(names, value)`
>`('thing', 'root') foo`
>`('thing', 'bar') baz`
>`('thing', 'root') flu`
>`('thing', 'bar') bat`
>`('thing', 'bar') bar`

The problem is that there is nothing in the stream that identifies that `('thing', 'bar') bat` and `('thing', 'bar') bar` don't share the same parent. The obvious solution is to emit valueless nodes, but that's a fundamental change to how **pyzpl** works.

I'm running into the issue where it appears you have a particular use-case in mind (I'm inferring streaming large volume ZPL), but the intrinsic assumptions are incompatible with my use-case (config file parsing). What am I missing?

**Comment by mbarkhau** [comment]
The first thing I would say, is to not change the behaviour of the existing `load` and `load_stream` functions. The library does appear to have at least a few users and I don't want to break anything for them. Adding a new function is not a problem though. 

The use case for `load_stream` is indeed to load an arbitrary amount of data, or put differently to not have to load an entire document into memory all at once.

I don't quite see how this use case is incompatible with config file parsing, notice that the existing `load` function uses the `load_stream` function.

I think the issue is not the use case (streaming data vs. config parsing) but rather the structure of the data that you're trying to parse. The current functions don't allow for a property to have both a value as well as child properties.

How about something like this.

```python
In [11]: import pyzpl
In [12]: with open("config.zpl") as fh:
     ...     cfg = pyzpl.parse(fh)
In [13]: cfg
Out[13]: <pyzpl.PyZPLTree object at 0x7fe11dc04dd8>
In [14]: cfg.get('thing')
Out[14]: 'foo'
In [15]: list(cfg.iter('thing'))
Out[15]: ['foo', 'flu']
In [16]: cfg.get('thing:bar')
Out[16]: 'baz'
In [17]: list(cfg.iter('thing:bar'))
Out[17]: ['baz', 'bat', 'bar']
```

Note that `:` (colon) is not a valid character for ZPL property names, so it can be used as a separator for the query string. From the spec: 

```
name = *name-char
name-char = ALPHA | DIGIT | "$" | "-" | "_" | "@" | "." | "&" | "+" | "/"
```

**Comment by jwmelto** [comment]
I suspected that changing existing behavior was bad. What do you think about allowing selectable behavior via keyword argument? That seems to be consistent with the encoding parameter.

Note in your suggestion, you are still losing the context that the three `bar` attributes belong to three different `thing` blocks. There is a significant difference to one block having three `bar` attributes and three blocks each having a different attribute.

I'm not sure how to express a query for a sub-block with a value, other than query for (and return) the sub-block, then retrieve attributes from it.

**Comment by mbarkhau** [comment]
> There is a significant difference to one block having three bar attributes and three blocks each having a different attribute.

Perhaps the way to distinguish these cases is not in the query string, but rather in the form that the result takes. If you do go the route of trying to express the difference in the query string, I would suggest having a look at how this might be expressed with css selectors (of course the separators would have to be different).

**Comment by jwmelto** [comment]
#2

**Comment by mbarkhau** [comment]
@jwmelto I made a beta release, which you can find here: https://pypi.org/project/pyzpl/201902.2b0/

You can install it with `pip install pyzpl==201902.2b0`. Please report if you find any issues.
